# Generated by Django 2.2.5 on 2019-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
